### ISSUE TITLE
Alternative country names?

### ISSUE THREAD

**Issue by vorg** [EvanHahn/iso-3166-country-list#1]
What about including alternative country names resolving to the same country code e.g:

USA  = United States = US
UK  = United Kingdom = UK
U.K. = United Kingdom = UK
Russia = Russian Federation = RU
North Korea = Democratic People's Republic of Korea = KP

**Comment by vorg** [comment]
After making my own alternative country names list, i'm no longer sure if that's the right place to add it here. It's iso-3166 in the end. Somebody will always find a new way to name a country...

**Comment by vorg** [comment]
Currently used country list

``` json
var AlternativeCountryNames = {
  "Iran"                : "Iran, Islamic Republic of",
  "North Korea"         : "Korea, Democratic People's Republic of",
  "Palestine"           : "Palestine, State of",
  "Palestinian Territory, Occupied" : "Palestine, State of",
  "Russia"              : "Russian Federation",
  "Saint Kitts-Nevis"   : "Saint Kitts and Nevis",
  "Syria"               : "Syrian Arab Republic",
  "U.K."                : "United Kingdom",
  "USA"                 : "United States"
};
```

**Comment by EvanHahn** [comment]
I think you're right—this is out of the scope of this module. I'll close this. I'm happy to help you build a companion library.
